# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63ecd898ddf69248d5c0dcf04bdaa804a27b4848d51755cf8ff9a6197040e24a350978c8a95648730cb9d67ad97ae1a1032c173d35ceea1a583b01051fcda80e

test:
  secret_key_base: 506b2ae55978616225c5010803d9277437b72004ac91c8bb75d202434ae548c21d33e2647d7af5fe5b57477d419775a3e6c8e45735da90e020b37ec362009192

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
